spring:
  r2dbc:
    url: r2dbc:mariadb://localhost:3306/myDB
    username: poly
    password: 1234

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

server:
  port: 11000



